### ISSUE TITLE
Image size is triple the quoted 30MB

### ISSUE THREAD

**Issue by rbirkby** [sekka1/aws-cli-docker#1]
``` bash
$ docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
awscli                        latest              a9875f2afd9b        4 seconds ago       93.69 MB
```

**Comment by sekka1** [comment]
Docker hub reports it as 30MB.  https://hub.docker.com/r/garland/aws-cli-docker/tags/  and my local machine like yours reports 93MB.  Maybe Docker hub is calculating it wrong.

Ive played around with removing the cache and stuff but it only lowers it a little bit.  Ive updated the doc to reflect the new 87MB size.
